services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "products"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "products"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    networks:
      app:
        ipv4_address: 10.25.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d products"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.0.0/16
          gateway: 10.25.0.1

volumes:
  postgres-data:
    driver: local
